// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;


public class Protocol : ProtocolBase
{
    public static Protocol Instance = new Protocol();
    private Protocol()
    {
        Protocol.SetProtocol<clientBtn>(clientBtn.Tag);
        Protocol.SetRequest<SprotoType.clientBtn.request>(clientBtn.Tag);

        Protocol.SetProtocol<clientControl>(clientControl.Tag);
        Protocol.SetRequest<SprotoType.clientControl.request>(clientControl.Tag);

        Protocol.SetProtocol<gameTick>(gameTick.Tag);
        Protocol.SetRequest<SprotoType.gameTick.request>(gameTick.Tag);

        Protocol.SetProtocol<handshake>(handshake.Tag);
        Protocol.SetRequest<SprotoType.handshake.request>(handshake.Tag);

        Protocol.SetProtocol<heartbeat>(heartbeat.Tag);
        Protocol.SetRequest<SprotoType.heartbeat.request>(heartbeat.Tag);
        Protocol.SetResponse<SprotoType.heartbeat.response>(heartbeat.Tag);

        Protocol.SetProtocol<matchMsg>(matchMsg.Tag);
        Protocol.SetRequest<SprotoType.matchMsg.request>(matchMsg.Tag);

        Protocol.SetProtocol<quit>(quit.Tag);

        Protocol.SetProtocol<restoreStates>(restoreStates.Tag);
        Protocol.SetRequest<SprotoType.restoreStates.request>(restoreStates.Tag);

        Protocol.SetProtocol<usersInfoMsg>(usersInfoMsg.Tag);
        Protocol.SetRequest<SprotoType.usersInfoMsg.request>(usersInfoMsg.Tag);

        Protocol.SetProtocol<waitforstart>(waitforstart.Tag);
        Protocol.SetRequest<SprotoType.waitforstart.request>(waitforstart.Tag);

    }

    public class clientBtn
    {
        public const int Tag = 4;
    }

    public class clientControl
    {
        public const int Tag = 1;
    }

    public class gameTick
    {
        public const int Tag = 3;
    }

    public class handshake
    {
        public const int Tag = 6;
    }

    public class heartbeat
    {
        public const int Tag = 9;
    }

    public class matchMsg
    {
        public const int Tag = 5;
    }

    public class quit
    {
        public const int Tag = 2;
    }

    public class restoreStates
    {
        public const int Tag = 10;
    }

    public class usersInfoMsg
    {
        public const int Tag = 7;
    }

    public class waitforstart
    {
        public const int Tag = 8;
    }

}