USE [master]
GO
/****** 对象:  Database [QPPlatformManagerDB_HideSeek]    脚本日期: 04/25/2011 17:01:53 ******/
CREATE DATABASE [QPPlatformManagerDB_HideSeek] ON  PRIMARY 
( NAME = N'QPPlatformManagerDB_HideSeek', FILENAME = N'C:\数据库\QPPlatformManagerDB_HideSeek.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QPPlatformManagerDB_HideSeek_log', FILENAME = N'C:\数据库\QPPlatformManagerDB_HideSeek_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'QPPlatformManagerDB_HideSeek', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QPPlatformManagerDB_HideSeek].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ARITHABORT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET  READ_WRITE 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET RECOVERY FULL 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET  MULTI_USER 
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QPPlatformManagerDB_HideSeek] SET DB_CHAINING OFF 